"""
Spin motors for 1 minute
"""
from machine import Pin, PWM
from time import sleep, ticks_ms

# Motor 1 Config
INA_LEFT = Pin(7, Pin.OUT)
INB_LEFT = Pin(8, Pin.OUT)
INA_LEFT.off()
INB_LEFT.off()
PWM_LEFT = PWM(Pin(6))
PWM_LEFT.freq(1000)

# Motor 2 Config
INA_RIGHT = Pin(20, Pin.OUT)
INB_RIGHT = Pin(19, Pin.OUT)
INA_RIGHT.off()
INB_RIGHT.off()
PWM_RIGHT = PWM(Pin(21))
PWM_RIGHT.freq(1000)


#Motor 1
INB_LEFT.on() #forward
#Motor 2
INB_RIGHT.on() #forward



#The following code was generated by Chat GPT
#from prompt "How to get following code to sget
#wheels to speed up and slow down in four seconds:
#and "Does this python code spin the wheels for one minute?"

# Run at 50% duty cycle for one minute
PWM_LEFT.duty_u16(int(65025 / 2))
PWM_RIGHT.duty_u16(int(65025 / 2))
sleep(60)  # Keep running for 60 seconds

# Stop the motors after one minute
PWM_LEFT.duty_u16(0)
PWM_RIGHT.duty_u16(0)


